const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHMENTS = "NEW_ATTACHMENTS";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_MESSAGE = "NEW_MESSAGE";
const NEW_REQUEST = "NEW_REQUEST";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENTS,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  START_TYPING,
  STOP_TYPING,
  NEW_MESSAGE,
};
